-- MySQL Script generated by MySQL Workbench
-- Sun Oct 21 17:15:13 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema b1online
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema b1online
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `b1online` DEFAULT CHARACTER SET utf8 ;
USE `b1online` ;

-- -----------------------------------------------------
-- Table `b1online`.`instruction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b1online`.`instruction` (
  `instructionid` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `author` VARCHAR(100) NULL DEFAULT NULL,
  `content` TEXT NULL DEFAULT NULL,
  `createddate` TIMESTAMP NULL DEFAULT NULL,
  `type` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`instructionid`))
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `b1online`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b1online`.`user` (
  `userid` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `fullname` VARCHAR(100) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `username` VARCHAR(100) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `password` VARCHAR(100) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `sex` BIGINT(1) NULL DEFAULT NULL,
  `address` VARCHAR(200) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `email` VARCHAR(150) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `createddate` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`userid`))
  ENGINE = InnoDB
  AUTO_INCREMENT = 4
  DEFAULT CHARACTER SET = utf8
  COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `b1online`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b1online`.`comment` (
  `commentid` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `content` TEXT NULL DEFAULT NULL,
  `userid` BIGINT(20) NULL DEFAULT NULL,
  `instructionid` BIGINT(20) NULL DEFAULT NULL,
  `createddate` TIMESTAMP NULL DEFAULT NULL,
  `modifydate` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`commentid`),
  INDEX `fk_comment_user1_idx` (`userid` ASC),
  INDEX `fk_comment_instruction1_idx` (`instructionid` ASC),
  CONSTRAINT `fk_comment_instruction1`
  FOREIGN KEY (`instructionid`)
  REFERENCES `b1online`.`instruction` (`instructionid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_user1`
  FOREIGN KEY (`userid`)
  REFERENCES `b1online`.`user` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `b1online`.`examination`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b1online`.`examination` (
  `examinationid` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL DEFAULT NULL,
  `createddate` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`examinationid`))
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `b1online`.`examinationquestion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b1online`.`examinationquestion` (
  `examinationquestionid` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `audio` VARCHAR(255) NULL DEFAULT NULL,
  `question` TEXT NULL DEFAULT NULL,
  `paragraph` TEXT NULL DEFAULT NULL,
  `option1` VARCHAR(350) NULL DEFAULT NULL,
  `option2` VARCHAR(350) NULL DEFAULT NULL,
  `option3` VARCHAR(350) NULL DEFAULT NULL,
  `option4` VARCHAR(350) NULL DEFAULT NULL,
  `answer` VARCHAR(50) NULL DEFAULT NULL,
  `examinationid` BIGINT(20) NULL DEFAULT NULL,
  `createddate` TIMESTAMP NULL DEFAULT NULL,
  `type` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`examinationquestionid`),
  INDEX `fk_examinationquestion_examination1_idx` (`examinationid` ASC),
  CONSTRAINT `fk_examinationquestion_examination1`
  FOREIGN KEY (`examinationid`)
  REFERENCES `b1online`.`examination` (`examinationid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `b1online`.`exercise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b1online`.`exercise` (
  `exerciseid` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(250) NULL DEFAULT NULL,
  `createddate` TIMESTAMP NULL DEFAULT NULL,
  `type` VARCHAR(50) NULL DEFAULT NULL,
  `author` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`exerciseid`))
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `b1online`.`exercisequestion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b1online`.`exercisequestion` (
  `exercisequestionid` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `audio` VARCHAR(255) NULL DEFAULT NULL,
  `question` TEXT NULL DEFAULT NULL,
  `option1` VARCHAR(350) NULL DEFAULT NULL,
  `option2` VARCHAR(350) NULL DEFAULT NULL,
  `option3` VARCHAR(350) NULL DEFAULT NULL,
  `option4` VARCHAR(350) NULL DEFAULT NULL,
  `answer` VARCHAR(50) NULL DEFAULT NULL,
  `exerciseid` BIGINT(20) NULL DEFAULT NULL,
  `createddate` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`exercisequestionid`),
  INDEX `fk_exercisequestion_exercise1_idx` (`exerciseid` ASC),
  CONSTRAINT `fk_exercisequestion_exercise1`
  FOREIGN KEY (`exerciseid`)
  REFERENCES `b1online`.`exercise` (`exerciseid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `b1online`.`result`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b1online`.`result` (
  `resultid` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `listenscope` INT(11) NULL DEFAULT NULL,
  `readscope` INT(11) NULL DEFAULT NULL,
  `writescope` INT(11) NULL DEFAULT NULL,
  `speakscope` INT(11) NULL DEFAULT NULL,
  `userid` BIGINT(20) NULL DEFAULT NULL,
  `examinationid` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`resultid`),
  INDEX `fk_result_user1_idx` (`userid` ASC),
  INDEX `fk_result_examination1_idx` (`examinationid` ASC),
  CONSTRAINT `fk_result_examination1`
  FOREIGN KEY (`examinationid`)
  REFERENCES `b1online`.`examination` (`examinationid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_result_user1`
  FOREIGN KEY (`userid`)
  REFERENCES `b1online`.`user` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `b1online`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b1online`.`role` (
  `roleid` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`roleid`))
  ENGINE = InnoDB
  AUTO_INCREMENT = 3
  DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `b1online`.`userrole`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `b1online`.`userrole` (
  `userid` BIGINT(20) NOT NULL,
  `roleid` BIGINT(20) NOT NULL,
  INDEX `fk_userrole_user_idx` (`userid` ASC),
  INDEX `fk_userrole_role1_idx` (`roleid` ASC),
  CONSTRAINT `fk_userrole_role1`
  FOREIGN KEY (`roleid`)
  REFERENCES `b1online`.`role` (`roleid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_userrole_user`
  FOREIGN KEY (`userid`)
  REFERENCES `b1online`.`user` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
